### ISSUE TITLE
Problem with AOT compilation in angular4

### ISSUE THREAD

**Issue by dieguisherrera** [NMilicic/ngx-bootstrap-product-tour#1]
The problem occurs when you call tourService.start() or tourService.start At().
As the directive is a dinamycaly created component, in AOT the following problem shows:

ERROR Error: No component factory found for t. Did you add it to @NgModule.entryComponents?

The solution is simple https://hassantariqblog.wordpress.com/2017/02/12/angular2-error-no-component-factory-found-did-you-add-it-to-ngmodule-entrycomponents/

Is necessary to add in the ngx-bootstrap-product-tour.module.ts file the following code next to declarations in @NgModule declaration

entryComponents: [
    NgxBootstrapProductTourDirective,
    NgxBootstrapProductTourStepComponent
  ],

**Comment by Chej0** [comment]
This Solution is not working for Me. It looks like angular does not find the NgxBootstrapProductTourDirective, NgxBootstrapProductTourStepComponent files

Am I importing the files correctly?

My code is atached
![Captura](https://user-images.githubusercontent.com/26882572/69376916-d35a4380-0c70-11ea-83c4-b3c250e79e13.PNG)


This is the importing lines
```
import { NgxBootstrapProductTourModule } from 'ngx-bootstrap-product-tour';
import { NgxBootstrapProductTourDirective } from 'ngx-bootstrap-product-tour/ngx-bootstrap-product-tour.directive';
import { NgxBootstrapProductTourStepComponent } from 'ngx-bootstrap-product-tour/ngx-bootstrap-product-tour-step/ngx-bootstrap-product-tour-step.component';
```


And This is my compiling error when I try ng serve -environment=dev

```
ERROR in ./src/app/dashboard/dashboard.module.ts
Module not found: Error: Can't resolve 'ngx-bootstrap-product-tour/ngx-bootstrap-product-tour-step/ngx-bootstrap-product-tour-step.component' in 'C:\Users\Admin\Desktop\TourApp\src\app\dashboard'
```
