### ISSUE TITLE
Support for Angular 5

### ISSUE THREAD

**Issue by ritmittal2682** [NMilicic/ngx-bootstrap-product-tour#3]
Looks like this component is not compatible with Angular 5. Can you please help upgrade it to Angular 5 as well. It uses <template> which is not supported in Angular 5.

Gettig below AOT error while adding the module in App module.

WARNING in ./node_modules/ngx-bootstrap-product-tour/node_modules/@angular/core/@angular/core.es5.js
5660:15-36 Critical dependency: the request of a dependency is an expression

**Comment by NMilicic** [comment]
@ritmittal2682 Should be fixed with #6 
I published it on npm under version 2.0.0 so pls update your's package.json
