### ISSUE TITLE
Tour spanning multiple components

### ISSUE THREAD

**Issue by suparnavg** [NMilicic/ngx-bootstrap-product-tour#9]
Hi @NMilicic , I was wondering if this is possible, as I did not see it in the docs.

I have a tour that spans a parent component and its child component. For e.g. Step 1 is anchored to a div in the parent component - on clicking "Next", Step 2 (anchored to a div in the child component) should be shown - can a tour like this be implemented using this package?

Thank you for your help!

**Comment by nfgallimore** [comment]
Am interested in this as well. This is why I gave up using intro.js
